Добавил ридми в раздел коллекции промптов
ai-forever/gigachain pull request #21
Opened 2023-09-28 10:00 UTC by Lytkini

Нужно поправить примеры.

2023-09-29 07:26 UTC, Rai220 requested changes

2023-09-29 07:26 UTC, Rai220 commented on hub/prompts/summarize/map_reduce/README.md
> +На вход в промпты можно передать переменную `text`, которая содержит текст, подлежащий суммаризации.
Не можно, а нужно :) Не передать нельзя

2023-09-29 07:26 UTC, Rai220 commented on hub/prompts/README.md
> +  > Подробнее о парсерах выходных данных читайте в [документации LangChain](https://python.langchain.com/docs/modules/model_io/output_parsers/).
На нашей стороне эта штука тоже есть - docs/docs_skeleton/docs/modules/model_io/output_parsers/index.mdx

Мы можем как-то на неё сослаться или нужно сначала из mdx сгенерировать html и где-то его захостить?

2023-10-02 12:57 UTC, Lytkini commented on hub/prompts/summarize/map_reduce/README.md
> +На вход в промпты можно передать переменную `text`, которая содержит текст, подлежащий суммаризации.
Поправил.

2023-10-02 12:58 UTC, Lytkini commented on hub/prompts/README.md
> +  > Подробнее о парсерах выходных данных читайте в [документации LangChain](https://python.langchain.com/docs/modules/model_io/output_parsers/).
Вообще да. Но я пока исправил ссылку на абсолютный путь до mdx-файла в репе. Относительный почему-то не сработал.

2023-10-02 13:19 UTC, merged